name: Maven CI with Nexus IQ

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #- name: Build with Maven - testing without this build
    #  run: mvn package -DskipTests --file pom.xml
    # - name: Nexus IQ Policy Evaluation
    #  uses: sonatype-nexus-community/iq-github-action@master
      - name: Sonatype GitHub Actions
        uses: sonatype/actions@v1.0.3
            
      
      with:
        serverUrl: ${{ secrets.iq_url }}
        username: ${{ secrets.iq_user }}
        password: ${{ secrets.iq_login }}
        applicationId: George_WebGoat__george-sntp
        stage: stage-release
        #target: george-sntp/George_WebGoat
