name: Maven CI with Nexus IQ

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Setup Sonatype CLI
      uses: sonatype/actions/setup-iq-cli@v1
      with:
          iq-cli-version: 1.179.0-01
    #- name: Build with Maven - testing without this build
    #  run: mvn package -DskipTests --file pom.xml
    # - name: Nexus IQ Policy Evaluation
    #  uses: sonatype-nexus-community/iq-github-action@master
    #- name: Sonatype GitHub Actions
    #  uses: sonatype/actions/evaluate@v1
    - name: Run Sonatype CLI
      uses: sonatype/actions/run-iq-cli@v1
      
      with:
        iq-server-url: ${{ secrets.iq_url }}
        username: ${{ secrets.iq_user }}
        password: ${{ secrets.iq_login }}
        application-id: George_WebGoat__george-sntp
        stage: build
        scan-targets: george-sntp/George_WebGoat/pom.xml
